version: '3'
services:
  mysql:
    image: mysql:5.7.26
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: sql-learn
    environment:
      MYSQL_DATABASE: sql-learn
      MYSQL_USER: joe
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 1333:3306

volumes:
  db_data:
