version: '3'
services:
  mysql:
    image: mysql:5.7.26
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: sql-learn
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - ./mysql/config:/etc/mysql/conf.d
    ports:
      - 3307:3306

volumes:
  db_data:
